name: Called Workflow
on:
  workflow_call:
    inputs:
      example_input:
        required: true
        type: string
jobs:
  example-job3:
    runs-on: ubuntu-latest
    outputs:
      output2: ${{ steps.fugafuga.outputs.output2 }}
    steps:
      - name: task4
        id: fugafuga
        run: |
          echo "Hello from called workflow"
          echo "output2=fugafuga" >> $GITHUB_OUTPUT
