name: Called Workflow
on:
  workflow_call:
    inputs:
      example_input:
        required: true
        type: string
    outputs:
      hogehoge:
        value: ${{ jobs.example-job3.outputs.hogehoge }}
      fugafuga:
        value: "aaaa${{ jobs.example-job3.outputs.fugafuga }}"

jobs:
  example-job3:
    runs-on: ubuntu-latest
    outputs:
      hogehoge: ${{ steps.fugafuga.outputs.hogehoge }}
      fugafuga: ${{ steps.fugafuga.outputs.fugafuga }}
    steps:
      - name: task4
        id: fugafuga
        run: |
          echo "Hello from called workflow"
          #VAR="echo \"output2=fugafuga\" >> \$GITHUB_OUTPUT"
          #echo $VAR
          #eval $VAR
          #cat $GITHUB_OUTPUT
          #FOO="output2"
          echo "${{ inputs.example_input }}=${{ inputs.example_input }}" >> $GITHUB_OUTPUT
