name: Called Workflow
on:
  workflow_call:
    inputs:
      example_input:
        required: true
        type: string
jobs:
  example-job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "Hello from called workflow"
          echo "output1=hogehoge" >> $GITHUB_OUTPUT

  example-job2:
    uses: ./.github/workflows/called_workflow2.yaml
    with:
      example_input: "example value"

