name: Called Workflow
on:
  workflow_call:
    inputs:
      example_input:
        required: true
        type: string
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello from called workflow"
          echo "output2=fugafuga" >> $GITHUB_OUTPUT
