name: Called Workflow
on:
  workflow_call:
    inputs:
      example_input:
        required: true
        type: string
    outputs:
      output3:
        value: ${{ jobs.example-job3.outputs.output3 }}
jobs:
  example-job3:
    runs-on: ubuntu-latest
    outputs:
      output2: ${{ steps.fugafuga.outputs.output2 }}
    steps:
      - name: task4
        id: fugafuga
        run: |
          echo "Hello from called workflow"
          VAR="output3"
          echo "${VAR}=fugafuga" | tee >> $GITHUB_OUTPUT
