name: Caller Workflow
on:
  workflow_dispatch:

jobs:
  call-workflow:
    name: Call workflow
    strategy:
      matrix:
        test:
          - value: hogehoge
          - value: fugafuga
    uses: ./.github/workflows/test.yaml
    with:
      example_input: ${{ matrix.test.value }}

  output-variables:
    name: Output variables
    needs: call-workflow
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
    steps:
      - name: Output variables
        run: |
          echo "hogehoge:  ${{ needs.call-workflow.outputs.hogehoge }}"
          echo "fugafuga:  ${{ needs.call-workflow.outputs.fugafuga }}"
