name: Test workflow

on:
  push:

jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
    uses: ./.github/workflows/test.yaml
    with:
      test1: "test ${{ matrix.version }}"
