name: Verify directory

on:
  push:

jobs:
  test-job1:
    name: Make directory
    runs-on: ubuntu-latest
    steps:
      - name: Make directory
        run: |
          pwd
          mkdir hogehoge && cd hogehoge
          pwd
          echo "fugafuga" > test.txt
          cat test.txt
