name: Reusable workflow
on:
  workflow_call:
    inputs:
      example_input:
        required: true
        type: string
    outputs:
      hogehoge:
        value: ${{ jobs.example-job.outputs.hogehoge }}
      fugafuga:
        value: ${{ jobs.example-job.outputs.fugafuga }}

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      repository: kdkwakaba
    outputs:
      hogehoge: ${{ steps.hogehoge.outputs.hogehoge }}
      fugafuga: ${{ steps.hogehoge.outputs.fugafuga }}
    steps:
      - name: Add GITHUB_OUTPUT
        id: hogehoge
        run: echo "${{ inputs.example_input }}=${{ env.repository }}/${{ inputs.example_input }}" >> $GITHUB_OUTPUT

  #example-job2:
  #  uses: ./.github/workflows/called_workflow2.yaml
  #  strategy:
  #    matrix:
  #      target:
  #        - value: hogehoge
  #        - value: fugafuga
  #    #max-parallel: 1
  #  with:
  #    example_input: ${{ matrix.target.value }}


