name: workflow call test
on:
  workflow_call:
    inputs:
      test1:
        type: boolean
        required: false

jobs:
  test:
    name: test job
    runs-on: ubuntu-latest
    steps:
      - name: hogehoge
        run: echo ${{ inputs.test1 }}
