name: Called Workflow
on:
  workflow_call:
    outputs:
      output_value:
        description: 'An example output'
        value: ${{ steps.step1.outputs.output_value }}

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "output_value=Hello from called workflow" >> $GITHUB_OUTPUT
