name: workflow call test
on:
  workflow_call:

jobs:
  test:
    name: test job
    runs-on: ubuntu-latest
    steps:
      - name: hogehoge
        id: test1
        run: echo "hogehoge=aabbcc" >> $GITHUB_OUTPUT
