name: Caller Workflow
on: [push]

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Call reusable workflow
        uses: ./.github/workflows/test.yml
      - name: Use output from called workflow
        run: echo "The output is ${{ needs.call-workflow.outputs.output_value }}"
