name: Caller Workflow
on: [push]

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call reusable workflow
        uses: ./.github/workflows/test2.yaml

      - name: Use output from called workflow1
        run: echo "The output is ${{ needs.call-workflow.outputs.output_value1 }}"

      - name: Use output from called workflow
        run: echo "The output is ${{ needs.call-workflow.outputs.output_value2 }}"
