name: workflow call test
on:
  workflow_call:
    inputs:
      test:
        type: string
        required: true

jobs:
  test:
    name: test job
    runs-on: ubuntu-latest
    steps:
      - name: hogehoge
        id: test1
        run: echo "hogehoge=${{ inputs.test }}" >> $GITHUB_OUTPUT
