name: Windows Test

on:
  push:

jobs:
  job1:
    name: Execute job1
    runs-on: self-hosted
    steps:
      - name: Git clone
        uses: actions/checkout@v4
    
      - name: Build
        run: dotnet build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            bin/
            obj/
          retention-days: 30
