name: Windows Test

on:
  push:

jobs:
  job1:
    name: Execute job1
    runs-on: self-hosted
    steps:
      - name: Git clone
        uses: actions/checkout@v4
    
      - name: Build
        run: dotnet build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            bin/
            obj/
          retention-days: 30

  job2:
    name: Download and Run
    runs-on: self-hosted
    needs: job1
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Run application
        run: dotnet run --project gha-test.csproj
