name: Windows Test

on:
  push:

jobs:
  job1:
    name: Execute job1
    runs-on: self-hosted
    steps:
      - name: Git clone
        uses: actions/checkout@v4
    
      - name: Build
        run: dotnet build
